apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 1000']
