name: Node PR Checks

on:
  push:
    paths:
      - 'dashboard/*'
      - '.github/workflows/pr_push_checks_node.yaml'

concurrency:
  group: pr-node-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-npm:
    name: Running smoke test npm build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup NPM
        working-directory: dashboard
        run: |
          # installing updated npm

          # Verify npm works before capturing and ensure its stderr is inspectable later
          version="$(jq -r '.engines.npm' package.json)"
          npm --version 2>&1 1>/dev/null

          npm_version="$(npm --version)"
          echo "Bootstrapping npm $version (replacing $npm_version)..."
          npm install --unsafe-perm -g --quiet "npm@$version"

          # Verify npm works before capturing and ensure its stderr is inspectable later
          npm --version 2>&1 1>/dev/null
          echo "npm $(npm --version) installed"
      - name: Install NPM Dependencies
        working-directory: dashboard
        run: |
          npm i --legacy-peer-deps
      - name: Run NPM Build
        working-directory: dashboard
        run: |
          npm run build
