name: Go PR Checks

on:
  workflow_dispatch: {}

concurrency:
  group: pr-go-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  testing_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        folder: [cli, api, cmd, internal, provisioner]
    name: Running Go Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: porter-go-${{ hashFiles('**/go.sum') }}
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: go.mod
      - name: Download Go Modules
        run: go mod download
      - name: Run Go tests
        run: go test ./${{ matrix.folder }}/...
