name: Backend CI
on:
  - pull_request
jobs:
  testing_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        folder: [cli, api, cmd, internal, provisioner]
    name: Running Go Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: porter-go-${{ hashFiles('**/go.sum') }}
      - name: Download Go Modules
        run: go mod download
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - name: Run Go vet
        run: go vet ./...
      - name: Run Go tests
        run: go test ./${{ matrix.folder }}/...
