name: Backend CI
on:
  - pull_request
jobs:
  backend-tests:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.15.1'
    - run: go test ./...
